### ISSUE TITLE
aclocal: error: echo failed with exit status: 127

### ISSUE THREAD

**Issue by Mykola-Veryha** [znerol/libvmod-chromelogger#1]
git clone https://github.com/znerol/libvmod-chromelogger.git /libvmod-chromelogger
cd /libvmod-chromelogger && ./autogen.sh

I got this error

```
+ aclocal -I m4
aclocal: warning: couldn't open directory 'm4': No such file or directory
sh: autom4te: not found
aclocal: error: echo failed with exit status: 127
```

**Comment by znerol** [comment]
`autom4te` is a part of `autoconf`. Make sure to `apt install build-essential` if you are running some Debian based system (including Ubuntu, etc).
